# Generated by Django 4.0.4 on 2022-05-24 16:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_productos_cantidad_stock_productos_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos',
            name='img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
