# Generated by Django 4.0.4 on 2022-05-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_productos_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos',
            name='img',
            field=models.ImageField(upload_to='inventario'),
        ),
    ]
