# Generated by Django 4.0.4 on 2022-05-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('documento', models.IntegerField(default=0)),
                ('correo', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=30)),
                ('departamento', models.CharField(max_length=30)),
                ('ciudad', models.CharField(max_length=30)),
                ('telefono', models.IntegerField(default=0)),
            ],
        ),
    ]
