# Generated by Django 4.0.4 on 2022-05-31 15:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0002_alter_pedidos_ciudad_alter_pedidos_correo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='precio',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='producto',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
